### ISSUE TITLE
truncated wav files

### ISSUE THREAD

**Issue by stubblmg** [usc-imi/aeo-light#21] opened 2019-05-30 18:28 UTC
Wav files that we have created in aeo-light v 2.3.2 are showing up as truncated in both MediaInfo as well as BWF MetaEdit and rawcooked.

MediaInfo output in General section: IsTruncated: Yes

BWF MetaEdit Tech data: Errors: invalid Wave: truncated

I'm trying to figure out a workaround, but it would be ideal if the output direct from AEO-Light was not truncated.

The files play back normally and seem OK. 

Has anybody else run into this issue? I am unable to identify a setting in the GUI to prevent the files from appearing truncated.

Thanks,
Madison

**Comment by kieranjol** [comment] 2019-05-30 19:45
We have also noticed this but have not investigated too much,we assumed it was an issue with files created with older versions of aeolight?

**Comment by retokromer** [comment] 2019-05-30 19:50
It’s still the case.

**Comment by wilsbacher** [comment] 2019-05-31 07:52
Would you be willing to send us an sample wav?

thx
Greg

**Comment by kieranjol** [comment] 2019-05-31 08:35
P.s I am sure you've noticed that rawcooked refuses to process these files?

**Comment by retokromer** [comment] 2019-05-31 08:48
@kieranjol Also the current RAWcooked snapshot?

**Comment by kieranjol** [comment] 2019-05-31 09:25
We have definitely seen this issue but have not investigated much. We
assumed it was with older files and not with newer ones?

**Comment by stubblmg** [comment] 2019-05-31 16:37
Thanks for the comments. Here is the output from rawcooked:

C:\RAWcooked_CLI_18.10.1_Windows_x64>rawcooked --check 1 X:\AEO-Light\4K_test_film_opt\4K_test_film_opt_346_1500_DPX

Error: untested 4K_test_film_opt_346_1500_DPX\4K_test_film_opt_346_1500.wav Truncated WAV?.
Please contact info@mediaarea.net if you want support of such content.

Here is a link to download the wav file (it will be available for a week):
https://we.tl/t-HftvsZe0rg

**Comment by retokromer** [comment] 2019-05-31 16:42
>Here is a link to download the wav file (it will be available for a week):
>https://we.tl/t-HftvsZe0rg

cc @JeromeMartinez

**Comment by JeromeMartinez** [comment] 2019-05-31 16:57
the file is understood as truncated because the WAV chunk size is wrong (0x46 bytes less than reality), so the end of the bext chunk is not inside the WAV chunk (you also lose some bext data...)

```
0000000 WAVE (12 bytes)
0000000  Header (12 bytes)
0000000   Name:                                 RIFF
0000004   Size:                                 27720738 (0x01A6FC22)
[...]
1A6FC0C   History:                              A=PCM,F=96000,W=24,M=dual-mono
1A6FC2A ,T=A (70 bytes)
1A6FC2A  Header (8 bytes)
1A6FC2A   Name:                                 ,T=A
1A6FC2E   Size:                                 1278037829 (0x4C2D4F45)
1A6FC32  Unknown:                               (62 bytes)
```
Note at the end the History (from bext) is cut (bext chunk size is correct but limited by the upper box size), and the History remaining bytes are considered as a new chunk (truncated in that case).

BWF MetaEdit could be updated for fixing such issue, RAWcooked could be updated for handling such buggy file (maybe better to fix with BWF MetaEdit instead...), but it would be better to fix aeo-light with right WAV chunk size for new files.

**Comment by ziggyphenocious** [comment] 2019-05-31 17:04
I’ve been making lots of wav files from 4k 16 bit tiff files and have not noticed any truncated files or error messages.  Are you using dpx is or tiff as a source?

Craig

Craig Nichols
The Packard Humanities Institute

**Comment by retokromer** [comment] 2019-05-31 17:11
>but it would be better to fix aeo-light with right WAV chunk size for new files.

+1

>Are you using dpx is or tiff as a source?

With 4K 16 bit DPX I can reproduce the error (I don’t have 4K 16 bit TIFF at home).

Yet, why should this depend on the input format?

**Comment by sjohnson-imi** [comment] 2019-06-05 18:38
The WAV chunk size misreporting is fixed in v2.3.3 ; I've just put up executables for Windows and MacOS for v2.3.3 

Let me know if the problem persists.

https://github.com/usc-imi/aeo-light/releases/tag/2.3.3

**Comment by retokromer** [comment] 2019-06-06 06:16
Thank you very much indeed! I am travelling to Vienna for Orphans and therefore can test only next week. Sorry for that!

**Comment by retokromer** [comment] 2019-06-06 07:26
@sjohnson-imi Link on the [home page](https://usc-imi.github.io/aeo-light/) should be updated as well.

**Comment by kieranjol** [comment] 2019-06-06 08:00
> the file is understood as truncated because the WAV chunk size is wrong (0x46 bytes less than reality), so the end of the bext chunk is not inside the WAV chunk (you also lose some bext data...)
> 
> ```
> 0000000 WAVE (12 bytes)
> 0000000  Header (12 bytes)
> 0000000   Name:                                 RIFF
> 0000004   Size:                                 27720738 (0x01A6FC22)
> [...]
> 1A6FC0C   History:                              A=PCM,F=96000,W=24,M=dual-mono
> 1A6FC2A ,T=A (70 bytes)
> 1A6FC2A  Header (8 bytes)
> 1A6FC2A   Name:                                 ,T=A
> 1A6FC2E   Size:                                 1278037829 (0x4C2D4F45)
> 1A6FC32  Unknown:                               (62 bytes)
> ```
> 
> Note at the end the History (from bext) is cut (bext chunk size is correct but limited by the upper box size), and the History remaining bytes are considered as a new chunk (truncated in that case).
> 
> BWF MetaEdit could be updated for fixing such issue, RAWcooked could be updated for handling such buggy file (maybe better to fix with BWF MetaEdit instead...), but it would be better to fix aeo-light with right WAV chunk size for new files.

What would BWF metaedit need to do, just update the value to the correct one?

**Comment by JeromeMartinez** [comment] 2019-06-06 08:31
> What would BWF metaedit need to do, just update the value to the correct one?

Some heuristic tests for having good confidence this is the pattern of an issue (here: testing that the file is more coherent if level 2 chunk size has priority other level 1 chunk size), then update of the value to the correct one.

**Comment by sjohnson-imi** [comment] 2019-06-06 12:49
> @sjohnson-imi Link on the [home page](https://usc-imi.github.io/aeo-light/) should be updated as well.

Done.

**Comment by retokromer** [comment] 2019-06-06 12:49
@sjohnson-imi FYI: It was reported that the macOS installer crashes, but I cannot verify this now.

**Comment by sjohnson-imi** [comment] 2019-06-06 12:52
> @sjohnson-imi FYI: It was reported that the macOS installer crashes, but I cannot verify this now.

I cannot replicate. There is no installer. The .dmg contains just the .app

**Comment by retokromer** [comment] 2019-06-06 12:54
>I cannot replicate. There is no installer. The .dmg contains just the .app

I presume while opening the .dmg, but as said I cannot test it now on my end.

**Comment by JeromeMartinez** [comment] 2019-06-06 12:59
>  It was reported that the macOS installer crashes,

I tested on my macOS 10.12 and no crash. I guess it is specific to a platform version, need more details.

**Comment by sjohnson-imi** [comment] 2019-06-06 12:59
> I presume while opening the .dmg, but as said I cannot test it now on my end.

OK. The github version of the .dmg opens (and the app runs from the image) in my tests. So let me know what you find.

**Comment by wilsbacher** [comment] 2019-06-06 13:11
Confirming that 2.3.3 dmg  downloaded and opened without crashing on my MacPro (2018) running Mojave.

**Comment by retokromer** [comment] 2019-06-06 13:30
I confirm that it works on my end as well. It seems to me to be a hardware issue on the reporter’s computer (the ominous `Kernel stack memory corruption` message).

**Comment by ziggyphenocious** [comment] 2019-06-06 21:03
Install worked ok on my Mac Pro running Mojave.

Craig

**Closed** 2019-06-07 11:38 UTC
Labels: bug
